// <auto-generated />
using System;
using HealthCenter.Desktop.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthCenter.Desktop.Migrations
{
    [DbContext(typeof(HealthCenterDbContext))]
    partial class HealthCenterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("HealthCenter.Desktop.Database.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ScheduledTime");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("HealthCenter.Desktop.Database.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaymentMethod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.HasIndex("VisitId");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Amount = 150.00m,
                            CreatedAt = new DateTime(2026, 2, 16, 8, 35, 0, 0, DateTimeKind.Unspecified),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000004"),
                            PaidAt = new DateTime(2026, 2, 16, 8, 40, 0, 0, DateTimeKind.Unspecified),
                            PatientId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PaymentMethod = 1,
                            Status = 1,
                            TaxAmount = 22.50m,
                            VisitId = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            Amount = 200.00m,
                            CreatedAt = new DateTime(2026, 2, 15, 10, 25, 0, 0, DateTimeKind.Unspecified),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000004"),
                            PatientId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Status = 0,
                            TaxAmount = 30.00m,
                            VisitId = new Guid("30000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("HealthCenter.Desktop.Database.Entities.LabTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PerformedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultNotes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PerformedById");

                    b.HasIndex("RequestedById");

                    b.HasIndex("Status");

                    b.HasIndex("VisitId");

                    b.ToTable("LabTests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            CompletedAt = new DateTime(2026, 2, 14, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = new Guid("10000000-0000-0000-0000-000000000008"),
                            PerformedById = new Guid("00000000-0000-0000-0000-000000000005"),
                            RequestedAt = new DateTime(2026, 2, 14, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            RequestedById = new Guid("00000000-0000-0000-0000-000000000002"),
                            ResultNotes = "النتيجة: 6.2% - طبيعي بالنسبة لمريض سكري",
                            Status = 2,
                            TestName = "فحص السكر التراكمي Hba1c",
                            VisitId = new Guid("30000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("HealthCenter.Desktop.Database.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("BloodType")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContact")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedicalHistory")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FullName");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Address = "الرياض، حي الملز",
                            BloodType = "A+",
                            CreatedAt = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyContact = "0559876543",
                            FullName = "أحمد محمد علي",
                            Gender = 0,
                            PhoneNumber = "0501234567",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Address = "جدة، حي الروضة",
                            BloodType = "O-",
                            CreatedAt = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1990, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyContact = "0501234567",
                            FullName = "فاطمة خالد العمري",
                            Gender = 1,
                            PhoneNumber = "0559876543",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Address = "الدمام، حي الفيصلية",
                            BloodType = "B+",
                            CreatedAt = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1978, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyContact = "0554445566",
                            FullName = "عبدالله سعد الغامدي",
                            Gender = 0,
                            PhoneNumber = "0551112233",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Address = "مكة المكرمة، العزيزية",
                            BloodType = "AB+",
                            CreatedAt = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1995, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyContact = "0551112233",
                            FullName = "نورة عبدالرحمن القحطاني",
                            Gender = 1,
                            PhoneNumber = "0544445566",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Address = "أبها، حي المنهل",
                            BloodType = "O+",
                            CreatedAt = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1982, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyContact = "0561234567",
                            FullName = "محمد عبدالعزيز الشهري",
                            Gender = 0,
                            PhoneNumber = "0567778899",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Address = "الرياض، حي النخيل",
                            BloodType = "A-",
                            CreatedAt = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1988, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyContact = "0522223333",
                            FullName = "سارة أحمد الدوسري",
                            Gender = 1,
                            PhoneNumber = "0533334444",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Address = "الطائف، حي الشهداء",
                            BloodType = "B-",
                            CreatedAt = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1992, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyContact = "0533334444",
                            FullName = "خالد فهد المطيري",
                            Gender = 0,
                            PhoneNumber = "0522223333",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Address = "المدينة المنورة، حي العزيزية",
                            BloodType = "O+",
                            CreatedAt = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1975, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyContact = "0577778888",
                            FullName = "منى سليمان الحربي",
                            Gender = 1,
                            PhoneNumber = "0588889999",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Address = "جدة، حي السلامة",
                            BloodType = "AB-",
                            CreatedAt = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1987, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyContact = "0588889999",
                            FullName = "ياسر علي الزهراني",
                            Gender = 0,
                            PhoneNumber = "0577778888",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Address = "الخبر، حي الثقبة",
                            BloodType = "A+",
                            CreatedAt = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1993, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyContact = "0599998888",
                            FullName = "ريم محمد القرني",
                            Gender = 1,
                            PhoneNumber = "0511112222",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HealthCenter.Desktop.Database.Entities.QueueTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CallCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CalledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TicketNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.ToTable("QueueTickets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CallCount = 1,
                            CalledAt = new DateTime(2026, 2, 16, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            CompletedAt = new DateTime(2026, 2, 16, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 2, 16, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PatientId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Status = 6,
                            TicketNumber = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CallCount = 1,
                            CalledAt = new DateTime(2026, 2, 16, 8, 35, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 2, 16, 8, 10, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PatientId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Status = 5,
                            TicketNumber = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CallCount = 0,
                            CreatedAt = new DateTime(2026, 2, 16, 8, 20, 0, 0, DateTimeKind.Unspecified),
                            PatientId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Status = 0,
                            TicketNumber = 3
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            CallCount = 0,
                            CreatedAt = new DateTime(2026, 2, 16, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Status = 0,
                            TicketNumber = 4
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            CallCount = 0,
                            CreatedAt = new DateTime(2026, 2, 16, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            PatientId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Status = 0,
                            TicketNumber = 5
                        });
                });

            modelBuilder.Entity("HealthCenter.Desktop.Database.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "مدير النظام",
                            IsActive = true,
                            PasswordHash = "admin123",
                            Role = 0,
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "د. أحمد صالح",
                            IsActive = true,
                            PasswordHash = "doctor123",
                            Role = 2,
                            Username = "dr_ahmed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "الممرضة فاطمة",
                            IsActive = true,
                            PasswordHash = "nurse123",
                            Role = 3,
                            Username = "nurse_fatima"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "المحاسب عمر",
                            IsActive = true,
                            PasswordHash = "cashier123",
                            Role = 5,
                            Username = "cashier_omar"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "فني المختبر سالم",
                            IsActive = true,
                            PasswordHash = "tech123",
                            Role = 6,
                            Username = "tech_salem"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "م. الاستقبال نور",
                            IsActive = true,
                            PasswordHash = "rec123",
                            Role = 4,
                            Username = "rec_nour"
                        });
                });

            modelBuilder.Entity("HealthCenter.Desktop.Database.Entities.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Attachments")
                        .HasColumnType("TEXT");

                    b.Property<string>("BloodPressure")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NurseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prescriptions")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("NurseId");

                    b.HasIndex("PatientId");

                    b.HasIndex("VisitDate");

                    b.ToTable("Visits");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            BloodPressure = "120/80",
                            CreatedAt = new DateTime(2026, 2, 16, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "التهاب الحلق الحاد",
                            DoctorId = new Guid("00000000-0000-0000-0000-000000000002"),
                            HeartRate = 85,
                            Notes = "المريض يعاني من ارتفاع طفيف في درجة الحرارة",
                            NurseId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PatientId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Prescriptions = "Amoxicillin 500mg - 3 مرات يومياً لمدة 5 أيام",
                            Temperature = 38.2m,
                            VisitDate = new DateTime(2026, 2, 16, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            Weight = 70.0m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            BloodPressure = "150/95",
                            CreatedAt = new DateTime(2026, 2, 15, 10, 20, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "ارتفاع ضغط الدم",
                            DoctorId = new Guid("00000000-0000-0000-0000-000000000002"),
                            HeartRate = 72,
                            Notes = "ينصح بتقليل الملح في الطعام وممارسة الرياضة",
                            NurseId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PatientId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Prescriptions = "Amlodipine 5mg - مرة واحدة يومياً صباحاً",
                            Temperature = 36.8m,
                            VisitDate = new DateTime(2026, 2, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 95.5m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 2, 14, 11, 25, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "فحص دوري - السكري",
                            DoctorId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Notes = "مستوى السكر التراكمي مستقر، المتابعة بعد 3 أشهر",
                            NurseId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PatientId = new Guid("10000000-0000-0000-0000-000000000008"),
                            Prescriptions = "Metformin 500mg - مرتين يومياً مع الوجبات",
                            VisitDate = new DateTime(2026, 2, 14, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HealthCenter.Desktop.Database.Entities.Appointment", b =>
                {
                    b.HasOne("HealthCenter.Desktop.Database.Entities.User", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HealthCenter.Desktop.Database.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthCenter.Desktop.Database.Entities.Invoice", b =>
                {
                    b.HasOne("HealthCenter.Desktop.Database.Entities.User", "CreatedBy")
                        .WithMany("Invoices")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthCenter.Desktop.Database.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthCenter.Desktop.Database.Entities.Visit", "Visit")
                        .WithMany("Invoices")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Patient");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("HealthCenter.Desktop.Database.Entities.LabTest", b =>
                {
                    b.HasOne("HealthCenter.Desktop.Database.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthCenter.Desktop.Database.Entities.User", "PerformedBy")
                        .WithMany("PerformedLabTests")
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthCenter.Desktop.Database.Entities.User", "RequestedBy")
                        .WithMany("RequestedLabTests")
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthCenter.Desktop.Database.Entities.Visit", "Visit")
                        .WithMany("LabTests")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("PerformedBy");

                    b.Navigation("RequestedBy");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("HealthCenter.Desktop.Database.Entities.QueueTicket", b =>
                {
                    b.HasOne("HealthCenter.Desktop.Database.Entities.User", "Doctor")
                        .WithMany("QueueTickets")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HealthCenter.Desktop.Database.Entities.Patient", "Patient")
                        .WithMany("QueueTickets")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthCenter.Desktop.Database.Entities.Visit", b =>
                {
                    b.HasOne("HealthCenter.Desktop.Database.Entities.User", "Doctor")
                        .WithMany("Visits")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthCenter.Desktop.Database.Entities.User", "Nurse")
                        .WithMany()
                        .HasForeignKey("NurseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HealthCenter.Desktop.Database.Entities.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Nurse");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthCenter.Desktop.Database.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("QueueTickets");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("HealthCenter.Desktop.Database.Entities.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Invoices");

                    b.Navigation("PerformedLabTests");

                    b.Navigation("QueueTickets");

                    b.Navigation("RequestedLabTests");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("HealthCenter.Desktop.Database.Entities.Visit", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("LabTests");
                });
#pragma warning restore 612, 618
        }
    }
}
